services:
  warranty:
    build: .
    container_name: warranty-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./new_imports:/app/new_imports
    restart: unless-stopped
    environment:
  - ADMIN_USER=${pavelkja}
  - ADMIN_PASS=${Meopta2026}


